import './jquery.init.js';
import './jquery.attr.js';
import './jquery.css.js';
import './jquery.static.js';
import './jquery.events.js';
import './jquery.observe.js';
import './jquery.wait.js';
import './jquery.urls.js';
import './jquery.js';
