import './jquery.init';
import './jquery.attr';
import './jquery.css';
import './jquery.static';
import './jquery.events';
import './jquery.observe';
import './jquery.wait';
import './jquery.urls';
import './jquery';
